#!/bin/sh

dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus \
org.freedesktop.DBus.StartServiceByName \
string:org.freedesktop.Telepathy.MissionControl5 uint32:0 > /dev/null

