#!/bin/sh

OBEX_ROOT="$1"

cd "$OBEX_ROOT"

ln -s ../MyDocs/.documents Documents
ln -s ../MyDocs/.images Images
ln -s ../MyDocs/.sounds "Audio clips"
ln -s ../MyDocs/.camera Camera
ln -s ../MyDocs/.videos "Video clips"
ln -s ../MyDocs Data
ln -s /media/mmc1 "Memory card"
